### ISSUE TITLE
Practica 4 y 5

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-teamreciclenexus#1]
[Reporte-LecturaEscritura.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-teamreciclenexus/files/15215543/Reporte-LecturaEscritura.pdf)

**Comment by ToniDepp** [comment]
Portada: Cumple con todos los elementos 25/25
Procedimiento: Detalla de manera clara 25/25
Figuras, ilustraciones y fotografías: 25/25
Resultados y conclusiones: 15/25

Resultado = 18%/20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
